- name: Create app package
  run: |
    mkdir -p build
    rsync -av --exclude='.git' --exclude='.github' --exclude='build' ./ build/

      - name: Upload Ravo
        uses: actions/upload-artifact@v4
        with:
          name: Ravo-App
          path: build/
